# Generated by Django 5.1.4 on 2024-12-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_address_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
